# Generated by Django 6.0.6 on 2026-06-23 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('robot_type', models.CharField(help_text='e.g. Da Vinci Xi, Mazor X', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='available', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoboticProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('procedure_type', models.CharField(max_length=200)),
                ('surgeon', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('duration_hours', models.FloatField(default=1)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='robotics.surgeryrobot')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
