# Generated by Django 6.0.6 on 2026-06-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientsessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsessionlog',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patientsessionlog',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsessionlog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
