# Generated by Django 6.0.6 on 2026-06-23 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('blood_pressure', models.FloatField(help_text='Systolic BP in mmHg')),
                ('sugar_level', models.FloatField(help_text='Blood sugar level in mg/dL')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('cholesterol', models.FloatField(help_text='Total cholesterol in mg/dL')),
                ('heart_rate', models.IntegerField(help_text='Heart rate in bpm')),
                ('disease_type', models.CharField(choices=[('diabetes', 'Diabetes'), ('heart_disease', 'Heart Disease'), ('hypertension', 'Hypertension'), ('kidney_disease', 'Kidney Disease')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20)),
                ('risk_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
