# Generated by Django 6.0.6 on 2026-06-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientsessionlog_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('patient', 'Patient')], max_length=20),
        ),
    ]
