# Generated by Django 6.0.6 on 2026-06-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_admissions', models.IntegerField(default=0)),
                ('total_discharges', models.IntegerField(default=0)),
                ('emergency_cases', models.IntegerField(default=0)),
                ('outpatient_visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quantity_consumed', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BedUtilizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('icu_occupied', models.IntegerField(default=0)),
                ('general_occupied', models.IntegerField(default=0)),
                ('emergency_occupied', models.IntegerField(default=0)),
                ('total_beds', models.IntegerField(default=0)),
                ('occupied_beds', models.IntegerField(default=0)),
                ('utilization_rate', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='DepartmentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('patient_count', models.IntegerField(default=0)),
                ('appointment_count', models.IntegerField(default=0)),
                ('bed_utilization', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('department_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_patients', models.IntegerField(default=0)),
                ('total_admissions', models.IntegerField(default=0)),
                ('total_discharges', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('bed_utilization_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
    ]
